
# =========================================================
# CIVICRESOLVE - APPLICATION CONFIGURATION
# =========================================================
spring.application.name=civicresolve
 
# =========================================================
# SERVER
# =========================================================

server.port=8080


# =========================================================
# MYSQL DATABASE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/civicresolve
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB


# =========================================================
# THYMELEAF
# =========================================================

spring.thymeleaf.cache=false


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized


# =========================================================
# CIVICRESOLVE APPLICATION SETTINGS
# =========================================================

civicresolve.complaint.id-prefix=CR
civicresolve.complaint.default-response-time-hours=48


# =========================================================
# LOGGING
# =========================================================

logging.level.com.civicresolve=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO